version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: mkdir -p /tmp/workspace && echo $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM > /tmp/workspace/docker-tag.txt
      - run: docker login quay.io/$CIRCLE_PROJECT_USERNAME -u $QUAY_USERNAME -p $QUAY_PASSWORD
      - run: docker build -t quay.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$(cat /tmp/workspace/docker-tag.txt) .
      - run: docker push quay.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$(cat /tmp/workspace/docker-tag.txt)
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-tag.txt
    test:
      docker:
        - image: circleci/node:12.13.0
      steps:
        - checkout
        - run: npm install
        - run: npm test
  # lint_js:
  #   docker:
  #     - image: circleci/node:8.11
  #   steps:
  #     - checkout
  #     - run: npm install
  #     - run: npm run lint:js:ci
  # lint_css:
  #   docker:
  #     - image: circleci/node:8.11
  #   steps:
  #     - checkout
  #     - run: npm install
  #     - run: npm run lint:css:ci

  # stg_lighthouse_task:
  #   docker:
  #     - image: circleci/node:10.16-browsers
  #   steps:
  #     - checkout
  #     - run: |
  #         export LHCI_SITES="[\"https://malibu-web.qtstage.io\"]"
  #         npx @lhci/cli@0.4.x autorun

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          context: quay-login
      # - lint_js
      # - lint_css
      # - stg_lighthouse_task
