asset_host: http://localhost:8080
sketches_host: https://quintype-demo.quintype.io
host_to_api_host:
  help.lvh.me: https://user-documentation.quintype.io
host_to_automatic_api_host:
  - "-web"
  - ".malibu"
domain_mapping:
  subdomain.lvh.me: subdomain
onesignal:
  app_id: "19d534f1-3f5d-4258-a5f4-9f322b6f54ba"
  safari_web_id: "web.onesignal.auto.37a647a2-1bdc-46a8-a505-4f4cc6400a46"
  is_enable: true
