theme: jekyll-theme-minimal
title: Malibu
description: Documentation for Building a Quintype publisher app on the Malibu Framework
logo: https://images.assettype.com/quintype-website/2018-10/013e8cbe-92b4-435f-bbbb-3e101efbc99a/quintype_logo.png

